RD2 = rd2 -r rd/rd2html-lib


all: DBI_SPEC.ja.html

DBI_SPEC.ja.html: DBI_SPEC.ja Makefile
	$(RD2) --with-css=rubyStyle.css --html-title='DBI Specification Version 0.5 (Draft)' DBI_SPEC.ja > DBI_SPEC.ja.html
